### ISSUE TITLE
couple of issues

### ISSUE THREAD

**Issue by feross** [qubyte/rel-payment#4]
- `reject` could get called more than once, because you're using `.once()` on separate EventEmitters, and you use `.on()` in one place, too.

- this doesn't support redirects, since node's `http` and `https` packages don't follow redirects by default. use something like `simple-get` or `got` to handle that for you.

- pretty sure that the check here (https://github.com/qubyte/rel-payment/blob/33ab5b3174b81f64e5080dce131f79943cad8bb9/index.js#L37-L39) is redundant because you check for that earlier.

- `res.headers.link` does not need to be `.split()` with your regex because the `parse-link-header` package already does that.

great work, might use this in `thanks`, but still considering it. cheers! ✨

**Comment by qubyte** [comment]
Apologies, this got lost in a wash of emails! I'm not concerned about resolve and reject being called multiple times (promises only honour the first call to one of them), but leaks are a concern, as are the rest of your points.

Thanks for the feedback. I'll address it all over the weekend. 😄

**Comment by qubyte** [comment]
Ah, one thing though, the split on the link headers is necessary, otherwise only one `rel="payment"` gets resolved (this libary is really intended for previous and next links etc. which are singular).

**Comment by qubyte** [comment]
Updates published as v0.0.3.
